org: hobbyist
app: cap101
service: cap101

plugins:
  - serverless-offline

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs20.x
  region: ap-southeast-2
  environment:
    POSTGRE_HOST: ${env:POSTGRE_HOST}
    POSTGRE_PORT: ${env:POSTGRE_PORT}
    POSTGRE_DB_NAME: ${env:POSTGRE_DB_NAME}
    POSTGRE_DB_USER: ${env:POSTGRE_DB_USER}
    POSTGRE_DB_PWD: ${env:POSTGRE_DB_PWD}
    SMTP_SERVICE: ${env:SMTP_SERVICE}
    SMTP_APP: ${env:SMTP_APP}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://barangay-santa-monica.vercel.app
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
        - Cookie
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowCredentials: true
      maxAge: 3600

package:
  individually: true
  exclude:
    - test/**
    - .git/**
    - .vscode/**
    - venv/**
    - coverage/**
    - undefined/**

functions:
  mainRoutes:
    handler: server.handler
    timeout: 28
    events:
      - httpApi:
          path: /{proxy+}
          method: any
