org: hobbyist
app: cap101
service: cap101

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs20.x
  region: ap-southeast-2
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5000/
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      maxAge: 3600

package:
  individually: true
  exclude:
    - test/**
    - .git/**
    - .vscode/**
    - venv/**
    - coverage/**

functions:
  mainRoutes:
    handler: src/app.handler
    timeout: 28
    events:
      - httpApi:
          path: /{proxy+}
          method: get
